apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  serviceAccountName: my-k8s-sa
  schedule: "*/2 * * * *"
  jobTemplate:
    metadata:
      labels:
        job-name: backup
    spec:
      template:
        spec:
          nodeSelector:
            iam.gke.io/gke-metadata-server-enabled: "true"
          containers:
            - name: backup
              image: backup:latest
              env:
                - name: URL
                  value: "" # needs connection string to postgres db
                - name: PORT
                  value: ":8000"
                - name: HOST
                  value: postgres-svc
                - name: USER
                  value: postgres
                - name: DB_NAME
                  value: todos
                - name: POSTGRES_PORT
                  value: "5432"
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-password
                      key: PASSWORD
                # - name:
                #   valueFrom:
          restartPolicy: OnFailure
