apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: 38 * * * * # fix
  jobTemplate:
    metadata:
      labels:
        job-name: backup
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: djblackett/add-reminder:v0.4
              env:
                - name: API_URL
                  value: http://todo-go-backend-svc:2345/todos
          restartPolicy: OnFailure
