name: Release application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: "dwk-cluster"
  GKE_ZONE: "northamerica-northeast1"
  IMAGE: dwk-environments
  SERVICE: dwk-environments
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - run: gcloud --quiet auth configure-docker

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'
          namespace: development

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Frontend
        run: docker build --tag "${{ secrets.DOCKER_USERNAME }}/frontend:${GITHUB_SHA}" ./frontend

      - name: Build Backend
        run: docker build --tag "${{ secrets.DOCKER_USERNAME }}/backend:${GITHUB_SHA}" ./backend


      - name: Push Frontend
        run: docker push "${{ secrets.DOCKER_USERNAME }}/frontend:${GITHUB_SHA}"

      - name: Push Backend
        run: docker push "${{ secrets.DOCKER_USERNAME }}/backend:${GITHUB_SHA}"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Deploy
        run: |-
          kustomize edit set image frontend=${{ secrets.DOCKER_USERNAME }}/frontend:${GITHUB_SHA} backend=${{ secrets.DOCKER_USERNAME }}/backend:${GITHUB_SHA}
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment frontend-deployment
          kubectl rollout status deployment backend-deployment
          kubectl get services -o wide
